repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
- repo: https://github.com/Vimjas/vint
  rev: v0.4a4
  hooks:
      - id: vint
        args: [init.vim]
        stages: ['commit-msg']
